chore(build): check .toml

diff --git a/buildpacks/go/bin/build b/buildpacks/go/bin/build
--- a/buildpacks/go/bin/build
+++ b/buildpacks/go/bin/build
@@ -13,7 +13,10 @@ mkdir -p "${go_layer_dir}"
 
 # determine go version provided during detection
 go_version=$(< "${plan_path}" yj -t | jq -r '.entries[] | select(.name == "go") | .version')
-remote_go_version=$(< "${go_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+remote_go_version='not found'
+if [[ -f "${go_layer_dir}.toml" ]]; then
+    remote_go_version=$(< "${go_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+fi
 if [[ "${go_version}" == "${remote_go_version}" ]] ; then
   echo "---> Reusing go"
 else
@@ -34,7 +37,10 @@ export GOPATH="${go_cache_layer_dir}"
 
 # Compares previous go.mod checksum to the current go.mod
 local_mod_checksum=$(sha256sum go.mod | cut -d ' ' -f 1 || echo 'not found')
-remote_mod_checksum=$(< "${go_cache_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+remote_mod_checksum='not found'
+if [[ -f "${go_cache_layer_dir}.toml" ]]; then
+    remote_mod_checksum=$(< "${go_cache_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+fi
 mkdir -p "${go_cache_layer_dir}"
 
 if [[ -f go.mod && "${local_mod_checksum}" == "${remote_mod_checksum}" ]] ; then
diff --git a/buildpacks/python/bin/build b/buildpacks/python/bin/build
--- a/buildpacks/python/bin/build
+++ b/buildpacks/python/bin/build
@@ -13,7 +13,10 @@ mkdir -p "${python_layer_dir}"
 
 # determine python version provided during detection
 python_version=$(< "${plan_path}" yj -t | jq -r '.entries[] | select(.name == "python") | .version')
-remote_python_version=$(< "${python_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+remote_python_version="not found"
+if [[ -f "${python_layer_dir}.toml" ]]; then
+    remote_python_version=$(< "${python_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+fi
 if [[ "${python_version}" == "${remote_python_version}" ]] ; then
   echo "---> Reusing python"
 else
@@ -37,7 +40,10 @@ PIP_WHEEL_FILENAME="pip-${PIP_VERSION}-py2.py3-none-any.whl"
 PIP_WHEEL_URL=https://buildpacks.drycc.cc/python/common/${PIP_WHEEL_FILENAME}
 PIP_WHEEL="${pip_layer_dir}/${PIP_WHEEL_FILENAME}"
 
-remote_pip_version=$(< "${pip_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+remote_pip_version='not found'
+if [[ -f "${pip_layer_dir}.toml" ]]; then
+    remote_pip_version=$(< "${pip_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+fi
 if [[ "${PIP_VERSION}" == "${remote_pip_version}" ]] ; then
   echo "---> Reusing pip"
 else
@@ -66,7 +72,10 @@ export PKG_CONFIG_PATH="${python_layer_dir}/lib/pkg-config:${PKG_CONFIG_PATH}"
 # Compares previous requirements checksum to the current requirements
 requirements_layer_dir="${layers_dir}/requirements"
 local_requirements_checksum=$(sha256sum requirements.txt | cut -d ' ' -f 1 || echo 'not found')
-remote_requirements_checksum=$(< "${requirements_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+remote_requirements_checksum='not found'
+if [[ -f "${requirements_layer_dir}.toml" ]]; then
+    remote_requirements_checksum=$(< "${requirements_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+fi
 mkdir -p "${requirements_layer_dir}"
 
 if [[ -f requirements.txt && "${local_requirements_checksum}" == "${remote_requirements_checksum}" ]] ; then
diff --git a/buildpacks/ruby/bin/build b/buildpacks/ruby/bin/build
--- a/buildpacks/ruby/bin/build
+++ b/buildpacks/ruby/bin/build
@@ -13,7 +13,10 @@ mkdir -p "${ruby_layer_dir}"
 
 # determine ruby version provided during detection
 ruby_version=$(< "${plan_path}" yj -t | jq -r '.entries[] | select(.name == "ruby") | .version')
-remote_ruby_version=$(< "${ruby_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+remote_ruby_version="not found"
+if [[ -f "${ruby_layer_dir}.toml" ]]; then
+    remote_ruby_version=$(< "${ruby_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+fi
 if [[ "${ruby_version}" == "${remote_ruby_version}" ]] ; then
   echo "---> Reusing ruby"
 else
@@ -38,7 +41,10 @@ export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${ruby_layer_dir}/lib"
 # Compares previous Gemfile.lock checksum to the current Gemfile.lock
 bundler_layer_dir="${layers_dir}/bundler"
 local_bundler_checksum=$(sha256sum Gemfile.lock | cut -d ' ' -f 1 || echo 'not found') 
-remote_bundler_checksum=$(< "${bundler_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+remote_bundler_checksum="not found"
+if [[ -f "${bundler_layer_dir}.toml" ]]; then
+    remote_bundler_checksum=$(< "${bundler_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+fi
 
 mkdir -p "${bundler_layer_dir}/bin"
 bundle config --local path "${bundler_layer_dir}" >/dev/null
