up php install ext extensions.json

diff --git a/buildpacks/php/bin/build b/buildpacks/php/bin/build
--- a/buildpacks/php/bin/build
+++ b/buildpacks/php/bin/build
@@ -15,7 +15,9 @@ bp_dir=$(
 arch=$(dpkg --print-architecture)  # amd64 arm64
 # 2. DOWNLOAD PHP
 php_layer_dir="${layers_dir}/php"
-mkdir -p "${php_layer_dir}"/{config,docs,ext}
+mkdir -p "${php_layer_dir}"/config
+extensions_layer_dir="${layers_dir}/extensions"
+mkdir -p "${extensions_layer_dir}"/{docs,ext}
 
 # determine php version provided during detection
 php_version=$(< "${plan_path}" yj -t | jq -r '.entries[] | select(.name == "php") | .version')
@@ -48,9 +50,9 @@ export PHP_PEAR_PHP_BIN="${php_layer_dir}/bin/php"
 export php_layer_dir="${php_layer_dir}"
 echo "Config pecl"
 pecl config-set php_dir "${php_layer_dir}"
-pecl config-set ext_dir "${php_layer_dir}"/ext
-pecl config-set doc_dir "${php_layer_dir}"/docs
 pecl config-set bin_dir "${php_layer_dir}"/bin
+pecl config-set ext_dir "${php_layer_dir}"/ext
+pecl config-set doc_dir "${extensions_layer_dir}"/docs
 EOL
 fi
 echo "---> Config php-fpm"
@@ -66,17 +68,32 @@ export PHP_PEAR_PHP_BIN="${php_layer_dir}/bin/php"
 export php_layer_dir="${php_layer_dir}"
 export php_version="${php_version}"
 
-echo "---> Config pecl"
-pecl config-set php_dir "${php_layer_dir}"
-pecl config-set ext_dir "${php_layer_dir}"/ext
-pecl config-set doc_dir "${php_layer_dir}"/docs
-
-# Install extensions
-# shellcheck disable=SC1090
-source "$bp_dir/bin/ext"
-install_xdebug
-install_gd
-
+# Compares previous extensions.json checksum to the current extensions.json
+local_extensions_checksum="$(sha256sum extensions.json | cut -d ' ' -f 1 || echo 'not found')"
+remote_extensions_checksum="not found"
+if [[ -f "${extensions_layer_dir}.toml" ]]; then
+    remote_extensions_checksum=$(< "${extensions_layer_dir}.toml" yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+fi
+if [[ -f extensions.json && "${local_extensions_checksum}" == "${remote_extensions_checksum}" ]] ; then
+  echo "---> Reusing extensions.json"
+else
+  echo "---> Config pecl"
+  pecl config-set php_dir "${php_layer_dir}"
+  pecl config-set bin_dir "${php_layer_dir}"/bin
+  pecl config-set ext_dir "${php_layer_dir}"/ext
+  pecl config-set doc_dir "${extensions_layer_dir}"/docs
+  echo "---> Installing extensions.json"
+  rm "${php_layer_dir}"/ext/* -rf
+  cp -f "${bp_dir}/config/php/php.ini" "${php_layer_dir}/config/"
+  # shellcheck disable=SC1090
+  source "$bp_dir/bin/ext"
+  ext_install
+  cat > "${extensions_layer_dir}.toml"<<EOL
+cache = true
+launch = true
+metadata = "${local_extensions_checksum}"
+EOL
+fi
 
 # Compares previous composer.json checksum to the current composer.json
 vendor_layer_dir="${layers_dir}/vendor"
